name: Build & Test for Linux
on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:

jobs:
  build_rs:
    name: Build & Tests on linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy
          bins: cargo-deny, clippy-sarif, sarif-fmt
          cache-target: debug

      - name: Build rorm
        run: cargo build -p rorm

      - name: Run cargo test
        run: cargo test --all

      - name: Run cargo deny check
        run: cargo deny check --hide-inclusion-graph

      - name: Run rust-clippy
        run: cargo clippy --workspace --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload clippy analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true